services:
    
  web: 
    build:
      context: ./docker-config/php
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./webApp:/var/www
      - ./docker-config/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "5173:5173"
    depends_on:
      - pgsql
    # restart: always

  nginx:
    image: nginx
    build: ./docker-config/nginx
    ports:
      - "80:80"
    volumes:
      - ./webApp:/var/www
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    # restart: always

  pgsql:
    image: postgres:17
    environment:
      POSTGRES_USER: navStupro
      POSTGRES_PASSWORD: navStupro
      PGPASSWORD: navStupro
      POSTGRES_DB: main
      TZ: "Asia/Tokyo"
    ports:
      - 54320:5432 #SQLと違うので注意
    volumes:
      - ./docker-config/pgsql/data:/var/lib/postgresql/data
      - ./docker-config/pgsql/logs:/var/log
    # restart: always